---
- name: Suche und installiere Paketaktualisierungen
  hosts: all
  become: true
  tasks:
    - name: apt update
      apt:
        update_cache: yes

    - name: apt dist-upgrade
      apt:
        upgrade: dist

    - name: apt autoremove
      apt:
        autoremove: yes

    - name: apt clean
      apt:
        clean: yes